# Generated by Django 5.2.1 on 2025-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], default='buyer', max_length=10),
        ),
    ]
