# Generated by Django 5.2.4 on 2025-07-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skin_type',
            field=models.CharField(choices=[('dry', 'dry'), ('oily', 'oily'), ('combintion', 'combintaion'), ('sensitive', 'snsitive')], default='oily', max_length=10),
        ),
    ]
