# Generated by Django 5.2.4 on 2025-07-26 08:28

import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_skin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='concern',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('acne', 'Acne (جوش)'), ('dullness', 'Dullness (کدر بودن پوست)'), ('wrinkles', 'Wrinkles & Fine Lines (چین و چروک)'), ('dark_spots', 'Dark Spots (لک\u200cهای تیره)'), ('redness', 'Redness (قرمزی پوست)'), ('pores', 'Large Pores (منافذ باز)'), ('uneven_tone', 'Uneven Skin Tone (ناهمواری رنگ پوست)'), ('blackheads', 'Blackheads (جوش سرسیاه)'), ('puffiness', 'Puffiness (پف پوست)'), ('dark_circles', 'Dark Circles (تیرگی دور چشم)')], max_length=93),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fragrance_free', 'Fragrance-Free (بدون عطر)'), ('alcohol_free', 'Alcohol-Free (بدون الکل)'), ('cruelty_free', 'Cruelty-Free (تست نشده روی حیوانات)'), ('vegan', 'Vegan (کاملاً گیاهی)'), ('paraben_free', 'Paraben-Free (بدون پارابن)'), ('non_comedogenic', 'Non-Comedogenic (نمسدودکننده منافذ نیست)'), ('dermatologist_tested', 'Dermatologist Tested (تایید شده توسط متخصص پوست)'), ('eco_friendly', 'Eco-Friendly (سازگار با محیط زیست)'), ('sulfate_free', 'Sulfate-Free (بدون سولفات)'), ('natural_ingredients', 'Natural Ingredients (ترکیبات طبیعی)')], max_length=142),
        ),
    ]
