# Generated by Django 5.2.4 on 2025-08-05 14:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='concern',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('acne', 'acne'), ('dullness', 'dullness'), ('wrinkles', 'wrinkles'), ('dark_spots', 'dark_spots'), ('redness', 'redness'), ('pores', 'pores'), ('uneven_tone', 'uneven_tone'), ('blackheads', 'blackheads'), ('puffiness', 'puffiness'), ('dark_circles', 'dark_circles')], max_length=93),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fragrance_free', 'fragrance_free'), ('alcohol_free', 'alcohol_free'), ('cruelty_free', 'cruelty_free'), ('vegan', 'vegan'), ('paraben_free', 'paraben_free'), ('non_comedogenic', 'non_comedogenic'), ('dermatologist_tested', 'dermatologist_tested'), ('eco_friendly', 'eco_friendly'), ('sulfate_free', 'sulfate_free'), ('natural_ingredients', 'natural_ingredients')], max_length=142),
        ),
    ]
