# Generated by Django 5.2.4 on 2025-07-27 08:13

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dry', 'dry'), ('oily', 'oily'), ('combintion', 'combintaion'), ('sensitive', 'sensitive')], max_length=29)),
                ('concern_targeted', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('acne', 'Acne (جوش)'), ('dullness', 'Dullness (کدر بودن پوست)'), ('wrinkles', 'Wrinkles & Fine Lines (چین و چروک)'), ('dark_spots', 'Dark Spots (لک\u200cهای تیره)'), ('redness', 'Redness (قرمزی پوست)'), ('pores', 'Large Pores (منافذ باز)'), ('uneven_tone', 'Uneven Skin Tone (ناهمواری رنگ پوست)'), ('blackheads', 'Blackheads (جوش سرسیاه)'), ('puffiness', 'Puffiness (پف پوست)'), ('dark_circles', 'Dark Circles (تیرگی دور چشم)')], max_length=93)),
                ('preferences', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fragrance_free', 'Fragrance-Free (بدون عطر)'), ('alcohol_free', 'Alcohol-Free (بدون الکل)'), ('cruelty_free', 'Cruelty-Free (تست نشده روی حیوانات)'), ('vegan', 'Vegan (کاملاً گیاهی)'), ('paraben_free', 'Paraben-Free (بدون پارابن)'), ('non_comedogenic', 'Non-Comedogenic (نمسدودکننده منافذ نیست)'), ('dermatologist_tested', 'Dermatologist Tested (تایید شده توسط متخصص پوست)'), ('eco_friendly', 'Eco-Friendly (سازگار با محیط زیست)'), ('sulfate_free', 'Sulfate-Free (بدون سولفات)'), ('natural_ingredients', 'Natural Ingredients (ترکیبات طبیعی)')], max_length=142)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
