# Generated by Django 5.2.4 on 2025-07-29 07:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='concern_targeted',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='skin_type',
        ),
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dry', 'dry'), ('oily', 'oily'), ('combination', 'combination'), ('sensitive', 'sensitive'), ('acne', 'acne'), ('dullness', 'dullness'), ('wrinkles', 'wrinkles'), ('dark_spots', 'dark_spots'), ('redness', 'redness'), ('pores', 'pores'), ('uneven_tone', 'uneven_tone'), ('blackheads', 'blackheads'), ('puffiness', 'puffiness'), ('dark_circles', 'dark_circles'), ('fragrance_free', 'fragrance_free'), ('alcohol_free', 'alcohol_free'), ('cruelty_free', 'cruelty_free'), ('vegan', 'vegan'), ('paraben_free', 'paraben_free'), ('non_comedogenic', 'non_comedogenic'), ('dermatologist_tested', 'dermatologist_tested'), ('eco_friendly', 'eco_friendly'), ('sulfate_free', 'sulfate_free'), ('natural_ingredients', 'natural_ingredients')], max_length=267),
        ),
    ]
