# Generated by Django 5.2.4 on 2025-07-28 06:28

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('cleanser', 'cleanser'), ('Toner-Essence', 'Toner-Essence'), ('Serum-Treatments', 'Serum-Treatments'), ('Moisturizer', 'Moisturizer'), ('Sunscreen', 'Sunscreen'), ('Exfoliator', 'Exfoliator'), ('Mask', 'Mask'), ('Eye-Care', 'Eye-Care')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('skin_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dry', 'dry'), ('oily', 'oily'), ('combintion', 'combintaion'), ('sensitive', 'sensitive')], max_length=29)),
                ('concern_targeted', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('acne', 'Acne (جوش)'), ('dullness', 'Dullness (کدر بودن پوست)'), ('wrinkles', 'Wrinkles & Fine Lines (چین و چروک)'), ('dark_spots', 'Dark Spots (لک\u200cهای تیره)'), ('redness', 'Redness (قرمزی پوست)'), ('pores', 'Large Pores (منافذ باز)'), ('uneven_tone', 'Uneven Skin Tone (ناهمواری رنگ پوست)'), ('blackheads', 'Blackheads (جوش سرسیاه)'), ('puffiness', 'Puffiness (پف پوست)'), ('dark_circles', 'Dark Circles (تیرگی دور چشم)')], max_length=93)),
                ('preferences', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fragrance_free', 'Fragrance-Free (بدون عطر)'), ('alcohol_free', 'Alcohol-Free (بدون الکل)'), ('cruelty_free', 'Cruelty-Free (تست نشده روی حیوانات)'), ('vegan', 'Vegan (کاملاً گیاهی)'), ('paraben_free', 'Paraben-Free (بدون پارابن)'), ('non_comedogenic', 'Non-Comedogenic (نمسدودکننده منافذ نیست)'), ('dermatologist_tested', 'Dermatologist Tested (تایید شده توسط متخصص پوست)'), ('eco_friendly', 'Eco-Friendly (سازگار با محیط زیست)'), ('sulfate_free', 'Sulfate-Free (بدون سولفات)'), ('natural_ingredients', 'Natural Ingredients (ترکیبات طبیعی)')], max_length=142)),
                ('ingredient', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hyaluronic_acid', 'Hyaluronic Acid (اسید هیالورونیک)'), ('glycerin', 'Glycerin (گلیسیرین)'), ('squalane', 'Squalane (اسکوالان)'), ('panthenol', 'Panthenol (پانتنول)'), ('aloe_vera', 'Aloe Vera (آلوئه\u200cورا)'), ('salicylic_acid', 'Salicylic Acid (اسید سالیسیلیک)'), ('glycolic_acid', 'Glycolic Acid (اسید گلیکولیک)'), ('lactic_acid', 'Lactic Acid (اسید لاکتیک)'), ('mandelic_acid', 'Mandelic Acid (اسید ماندلیک)'), ('azelaic_acid', 'Azelaic Acid (اسید آزلائیک)'), ('vitamin_c', 'Vitamin C (ویتامین سی)'), ('arbutin', 'Arbutin (آربوتین)'), ('kojic_acid', 'Kojic Acid (اسید کوجیک)'), ('licorice_extract', 'Licorice Extract (عصاره شیرین\u200cبیان)'), ('niacinamide', 'Niacinamide (نیاسینامید)'), ('zinc_oxide', 'Zinc Oxide (اکسید روی)'), ('titanium_dioxide', 'Titanium Dioxide (دی\u200cاکسید تیتانیوم)'), ('green_tea_extract', 'Green Tea Extract (عصاره چای سبز)'), ('vitamin_e', 'Vitamin E (ویتامین E)'), ('centella_asiatica', 'Centella Asiatica (سنتلا آسیاتیکا/علف ببر)'), ('rosehip_oil', 'Rosehip Oil (روغن نسترن وحشی)'), ('argan_oil', 'Argan Oil (روغن آرگان)'), ('tea_tree_oil', 'Tea Tree Oil (روغن درخت چای)'), ('chamomile_extract', 'Chamomile Extract (عصاره بابونه)'), ('caffeine', 'Caffeine (کافئین - ضد پف و تیرگی)'), ('retinol', 'Retinol (رتینول)'), ('retinaldehyde', 'Retinaldehyde (رتین\u200cآلدئید)'), ('bakuchiol', 'Bakuchiol (باکوچیول، جایگزین گیاهی رتینول)'), ('peptides', 'Peptides (پپتیدها)'), ('collagen', 'Collagen (کلاژن)'), ('dimethicone', 'Dimethicone (دیمتیکون - پایه سیلیکونی)'), ('mica', 'Mica (میکا - براق\u200cکننده)'), ('iron_oxides', 'Iron Oxides (رنگدانه\u200cهای اکسید آهن)'), ('talc', 'Talc (تالک)'), ('silica', 'Silica (سیلیکا)')], max_length=406)),
                ('rating', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product')),
            ],
        ),
    ]
