# Generated by Django 5.2.4 on 2025-07-29 06:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cleanser', 'cleanser'), ('Toner-Essence', 'Toner-Essence'), ('Serum-Treatments', 'Serum-Treatments'), ('Moisturizer', 'Moisturizer'), ('Sunscreen', 'Sunscreen'), ('Exfoliator', 'Exfoliator'), ('Mask', 'Mask'), ('Eye-Care', 'Eye-Care'), ('dry', 'dry'), ('oily', 'oily'), ('combination', 'combination'), ('sensitive', 'sensitive'), ('acne', 'acne'), ('dullness', 'dullness'), ('wrinkles', 'wrinkles'), ('dark_spots', 'dark_spots'), ('redness', 'redness'), ('pores', 'pores'), ('uneven_tone', 'uneven_tone'), ('blackheads', 'blackheads'), ('puffiness', 'puffiness'), ('dark_circles', 'dark_circles'), ('fragrance_free', 'fragrance_free'), ('alcohol_free', 'alcohol_free'), ('cruelty_free', 'cruelty_free'), ('vegan', 'vegan'), ('paraben_free', 'paraben_free'), ('non_comedogenic', 'non_comedogenic'), ('dermatologist_tested', 'dermatologist_tested'), ('eco_friendly', 'eco_friendly'), ('sulfate_free', 'sulfate_free'), ('natural_ingredients', 'natural_ingredients'), ('hyaluronic_acid', 'hyaluronic_acid'), ('glycerin', 'glycerin'), ('squalane', 'squalane'), ('panthenol', 'panthenol'), ('aloe_vera', 'aloe_vera'), ('salicylic_acid', 'salicylic_acid'), ('glycolic_acid', 'glycolic_acid'), ('lactic_acid', 'lactic_acid'), ('mandelic_acid', 'mandelic_acid'), ('azelaic_acid', 'azelaic_acid'), ('vitamin_c', 'vitamin_c'), ('arbutin', 'arbutin'), ('kojic_acid', 'kojic_acid'), ('licorice_extract', 'licorice_extract'), ('niacinamide', 'niacinamide'), ('zinc_oxide', 'zinc_oxide'), ('titanium_dioxide', 'titanium_dioxide'), ('green_tea_extract', 'green_tea_extract'), ('vitamin_e', 'vitamin_e'), ('centella_asiatica', 'centella_asiatica'), ('rosehip_oil', 'rosehip_oil'), ('argan_oil', 'argan_oil'), ('tea_tree_oil', 'tea_tree_oil'), ('chamomile_extract', 'chamomile_extract'), ('caffeine', 'caffeine'), ('retinol', 'retinol'), ('retinaldehyde', 'retinaldehyde'), ('bakuchiol', 'bakuchiol'), ('peptides', 'peptides'), ('collagen', 'collagen'), ('dimethicone', 'dimethicone'), ('mica', 'mica'), ('iron_oxides', 'iron_oxides'), ('talc', 'talc'), ('silica', 'silica')], max_length=761),
        ),
        migrations.AlterField(
            model_name='product',
            name='concern_targeted',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('acne', 'acne'), ('dullness', 'dullness'), ('wrinkles', 'wrinkles'), ('dark_spots', 'dark_spots'), ('redness', 'redness'), ('pores', 'pores'), ('uneven_tone', 'uneven_tone'), ('blackheads', 'blackheads'), ('puffiness', 'puffiness'), ('dark_circles', 'dark_circles')], max_length=93),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hyaluronic_acid', 'hyaluronic_acid'), ('glycerin', 'glycerin'), ('squalane', 'squalane'), ('panthenol', 'panthenol'), ('aloe_vera', 'aloe_vera'), ('salicylic_acid', 'salicylic_acid'), ('glycolic_acid', 'glycolic_acid'), ('lactic_acid', 'lactic_acid'), ('mandelic_acid', 'mandelic_acid'), ('azelaic_acid', 'azelaic_acid'), ('vitamin_c', 'vitamin_c'), ('arbutin', 'arbutin'), ('kojic_acid', 'kojic_acid'), ('licorice_extract', 'licorice_extract'), ('niacinamide', 'niacinamide'), ('zinc_oxide', 'zinc_oxide'), ('titanium_dioxide', 'titanium_dioxide'), ('green_tea_extract', 'green_tea_extract'), ('vitamin_e', 'vitamin_e'), ('centella_asiatica', 'centella_asiatica'), ('rosehip_oil', 'rosehip_oil'), ('argan_oil', 'argan_oil'), ('tea_tree_oil', 'tea_tree_oil'), ('chamomile_extract', 'chamomile_extract'), ('caffeine', 'caffeine'), ('retinol', 'retinol'), ('retinaldehyde', 'retinaldehyde'), ('bakuchiol', 'bakuchiol'), ('peptides', 'peptides'), ('collagen', 'collagen'), ('dimethicone', 'dimethicone'), ('mica', 'mica'), ('iron_oxides', 'iron_oxides'), ('talc', 'talc'), ('silica', 'silica')], max_length=406),
        ),
        migrations.AlterField(
            model_name='product',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fragrance_free', 'fragrance_free'), ('alcohol_free', 'alcohol_free'), ('cruelty_free', 'cruelty_free'), ('vegan', 'vegan'), ('paraben_free', 'paraben_free'), ('non_comedogenic', 'non_comedogenic'), ('dermatologist_tested', 'dermatologist_tested'), ('eco_friendly', 'eco_friendly'), ('sulfate_free', 'sulfate_free'), ('natural_ingredients', 'natural_ingredients')], max_length=142),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dry', 'dry'), ('oily', 'oily'), ('combination', 'combination'), ('sensitive', 'sensitive')], max_length=30),
        ),
    ]
