# Generated by Django 5.2.4 on 2025-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cleanser', 'cleanser'), ('Toner-Essence', 'Toner-Essence'), ('Serum-Treatments', 'Serum-Treatments'), ('Moisturizer', 'Moisturizer'), ('Sunscreen', 'Sunscreen'), ('Exfoliator', 'Exfoliator'), ('Mask', 'Mask'), ('Eye-Care', 'Eye-Care')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
