# Generated by Django 5.2.4 on 2025-07-26 10:04

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='concern_targeted',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('acne', 'Acne (جوش)'), ('dullness', 'Dullness (کدر بودن پوست)'), ('wrinkles', 'Wrinkles & Fine Lines (چین و چروک)'), ('dark_spots', 'Dark Spots (لک\u200cهای تیره)'), ('redness', 'Redness (قرمزی پوست)'), ('pores', 'Large Pores (منافذ باز)'), ('uneven_tone', 'Uneven Skin Tone (ناهمواری رنگ پوست)'), ('blackheads', 'Blackheads (جوش سرسیاه)'), ('puffiness', 'Puffiness (پف پوست)'), ('dark_circles', 'Dark Circles (تیرگی دور چشم)')], max_length=93),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hyaluronic_acid', 'Hyaluronic Acid (اسید هیالورونیک)'), ('glycerin', 'Glycerin (گلیسیرین)'), ('squalane', 'Squalane (اسکوالان)'), ('panthenol', 'Panthenol (پانتنول)'), ('aloe_vera', 'Aloe Vera (آلوئه\u200cورا)'), ('salicylic_acid', 'Salicylic Acid (اسید سالیسیلیک)'), ('glycolic_acid', 'Glycolic Acid (اسید گلیکولیک)'), ('lactic_acid', 'Lactic Acid (اسید لاکتیک)'), ('mandelic_acid', 'Mandelic Acid (اسید ماندلیک)'), ('azelaic_acid', 'Azelaic Acid (اسید آزلائیک)'), ('vitamin_c', 'Vitamin C (ویتامین سی)'), ('arbutin', 'Arbutin (آربوتین)'), ('kojic_acid', 'Kojic Acid (اسید کوجیک)'), ('licorice_extract', 'Licorice Extract (عصاره شیرین\u200cبیان)'), ('niacinamide', 'Niacinamide (نیاسینامید)'), ('zinc_oxide', 'Zinc Oxide (اکسید روی)'), ('titanium_dioxide', 'Titanium Dioxide (دی\u200cاکسید تیتانیوم)'), ('green_tea_extract', 'Green Tea Extract (عصاره چای سبز)'), ('vitamin_e', 'Vitamin E (ویتامین E)'), ('centella_asiatica', 'Centella Asiatica (سنتلا آسیاتیکا/علف ببر)'), ('rosehip_oil', 'Rosehip Oil (روغن نسترن وحشی)'), ('argan_oil', 'Argan Oil (روغن آرگان)'), ('tea_tree_oil', 'Tea Tree Oil (روغن درخت چای)'), ('chamomile_extract', 'Chamomile Extract (عصاره بابونه)'), ('caffeine', 'Caffeine (کافئین - ضد پف و تیرگی)'), ('retinol', 'Retinol (رتینول)'), ('retinaldehyde', 'Retinaldehyde (رتین\u200cآلدئید)'), ('bakuchiol', 'Bakuchiol (باکوچیول، جایگزین گیاهی رتینول)'), ('peptides', 'Peptides (پپتیدها)'), ('collagen', 'Collagen (کلاژن)'), ('dimethicone', 'Dimethicone (دیمتیکون - پایه سیلیکونی)'), ('mica', 'Mica (میکا - براق\u200cکننده)'), ('iron_oxides', 'Iron Oxides (رنگدانه\u200cهای اکسید آهن)'), ('talc', 'Talc (تالک)'), ('silica', 'Silica (سیلیکا)')], max_length=406),
        ),
        migrations.AddField(
            model_name='product',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fragrance_free', 'Fragrance-Free (بدون عطر)'), ('alcohol_free', 'Alcohol-Free (بدون الکل)'), ('cruelty_free', 'Cruelty-Free (تست نشده روی حیوانات)'), ('vegan', 'Vegan (کاملاً گیاهی)'), ('paraben_free', 'Paraben-Free (بدون پارابن)'), ('non_comedogenic', 'Non-Comedogenic (نمسدودکننده منافذ نیست)'), ('dermatologist_tested', 'Dermatologist Tested (تایید شده توسط متخصص پوست)'), ('eco_friendly', 'Eco-Friendly (سازگار با محیط زیست)'), ('sulfate_free', 'Sulfate-Free (بدون سولفات)'), ('natural_ingredients', 'Natural Ingredients (ترکیبات طبیعی)')], max_length=142),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dry', 'dry'), ('oily', 'oily'), ('combintion', 'combintaion'), ('sensitive', 'sensitive')], max_length=29),
        ),
    ]
