# Generated by Django 5.2.6 on 2025-09-09 20:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_seasons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all_seasons', 'All Seasons')], help_text='Select the seasons this product is most suitable for', max_length=39),
        ),
    ]
